# =============================================================
# MGA Trajectory — generated by MGA Trajectory Configurator
# Sequence: Earth → Venus → Venus → Venus → Jupiter
# =============================================================
import numpy as np
import matplotlib.pyplot as plt
from typing import List, Tuple
import tudatpy
from tudatpy.trajectory_design import transfer_trajectory
from tudatpy import constants
from tudatpy.dynamics import environment_setup
from tudatpy.util import result2array
from tudatpy.astro.time_representation import DateTime
import pygmo as pg


# -------------------------------------------------------------
# Helper: convert flat parameter list to Tudat format
# -------------------------------------------------------------
def convert_trajectory_parameters(transfer_trajectory_object, trajectory_parameters):
    node_times, leg_free_parameters, node_free_parameters = [], [], []
    departure_time = trajectory_parameters[0]
    times_of_flight_per_leg = trajectory_parameters[1:]
    node_times.append(departure_time)
    accumulated_time = departure_time
    for i in range(transfer_trajectory_object.number_of_nodes - 1):
        accumulated_time += times_of_flight_per_leg[i]
        node_times.append(accumulated_time)
    for i in range(transfer_trajectory_object.number_of_legs):
        leg_free_parameters.append([])
    for i in range(transfer_trajectory_object.number_of_nodes):
        node_free_parameters.append([])
    return node_times, leg_free_parameters, node_free_parameters


# -------------------------------------------------------------
# PyGMO problem class
# -------------------------------------------------------------
class TransferTrajectoryProblem:

    def __init__(self, transfer_trajectory_object,
                 departure_date_lb, departure_date_ub,
                 legs_tof_lb, legs_tof_ub):
        self.departure_date_lb = departure_date_lb
        self.departure_date_ub = departure_date_ub
        self.legs_tof_lb = legs_tof_lb
        self.legs_tof_ub = legs_tof_ub
        self.transfer_trajectory_function = lambda: transfer_trajectory_object

    def get_bounds(self):
        obj = self.transfer_trajectory_function()
        n = obj.number_of_nodes
        lower_bound = [0.0] * n
        upper_bound = [0.0] * n
        lower_bound[0] = self.departure_date_lb
        upper_bound[0] = self.departure_date_ub
        for i in range(obj.number_of_legs):
            lower_bound[i + 1] = self.legs_tof_lb[i]
            upper_bound[i + 1] = self.legs_tof_ub[i]
        return lower_bound, upper_bound

    def get_number_of_parameters(self):
        return self.transfer_trajectory_function().number_of_nodes

    def fitness(self, trajectory_parameters):
        traj = self.transfer_trajectory_function()
        node_times, leg_fp, node_fp = convert_trajectory_parameters(
            traj, trajectory_parameters)
        try:
            traj.evaluate(node_times, leg_fp, node_fp)
            delta_v = traj.delta_v
        except Exception:
            delta_v = 1e10
        return [delta_v]


# =============================================================
# Mission configuration
# =============================================================

central_body = "Sun"
transfer_body_order = ["Earth","Venus","Venus","Venus","Jupiter"]

# Departure orbit
departure_semi_major_axis = np.inf
departure_eccentricity    = 0

# Arrival orbit
arrival_semi_major_axis = 5452500000
arrival_eccentricity    = 0.98

# Create simplified system of bodies
bodies = environment_setup.create_simplified_system_of_bodies()

# Build leg and node settings
transfer_leg_settings, transfer_node_settings = (
    transfer_trajectory.mga_settings_unpowered_unperturbed_legs(
        transfer_body_order,
        departure_orbit=(departure_semi_major_axis, departure_eccentricity),
        arrival_orbit=(arrival_semi_major_axis, arrival_eccentricity),
    )
)

# Create transfer trajectory object
transfer_trajectory_object = transfer_trajectory.create_transfer_trajectory(
    bodies,
    transfer_leg_settings,
    transfer_node_settings,
    transfer_body_order,
    central_body,
)

# Launch window
departure_date_lb = DateTime(2020, 4, 6).to_epoch()
departure_date_ub = DateTime(2030, 12, 31).to_epoch()

# Time-of-flight bounds [days → seconds]
legs_tof_lb = np.zeros(4)
legs_tof_ub = np.zeros(4)
# Earth → Venus
legs_tof_lb[0] = 30 * constants.JULIAN_DAY
legs_tof_ub[0] = 303 * constants.JULIAN_DAY
# Venus → Venus
legs_tof_lb[1] = 30 * constants.JULIAN_DAY
legs_tof_ub[1] = 600 * constants.JULIAN_DAY
# Venus → Venus
legs_tof_lb[2] = 30 * constants.JULIAN_DAY
legs_tof_ub[2] = 1000 * constants.JULIAN_DAY
# Venus → Jupiter
legs_tof_lb[3] = 30 * constants.JULIAN_DAY
legs_tof_ub[3] = 1400 * constants.JULIAN_DAY


# =============================================================
# Optimization setup  (DE — Differential Evolution)
# =============================================================

optimizer = TransferTrajectoryProblem(
    transfer_trajectory_object,
    departure_date_lb, departure_date_ub,
    legs_tof_lb, legs_tof_ub,
)

prob           = pg.problem(optimizer)
algo           = pg.algorithm(pg.de(gen=10, seed=4444, F=0.5))
population_size = 20
pop            = pg.population(prob, size=population_size, seed=4444)

# =============================================================
# Run optimization
# =============================================================

number_of_evolutions = 800
individuals_list, fitness_list = [], []

for i in range(number_of_evolutions):
    pop = algo.evolve(pop)
    individuals_list.append(pop.champion_x)
    fitness_list.append(pop.champion_f)

print("Optimization complete")

# =============================================================
# Results
# =============================================================

from datetime import datetime, timedelta

# J2000 epoch: 1 January 2000, 12:00 TT
J2000 = datetime(2000, 1, 1, 12, 0, 0)

def epoch_to_date(epoch_seconds):
    """Convert Tudat epoch (seconds from J2000) to a calendar date string."""
    return (J2000 + timedelta(seconds=epoch_seconds)).strftime("%d %b %Y")

def tof_to_str(tof_seconds):
    """Format a time-of-flight in seconds as 'X days (Y months)'."""
    days = tof_seconds / constants.JULIAN_DAY
    months = days / 30.44
    return f"{days:.1f} days  (~{months:.1f} months)"

print("\n--- Champion ---")
print(f"Total ΔV          : {pop.champion_f[0]:.2f} m/s  ({pop.champion_f[0]/1000:.3f} km/s)")

best_x = pop.champion_x  # still in seconds
leg_names = "Earth→Venus, Venus→Venus, Venus→Venus, Venus→Jupiter".split(", ")

# Node dates
node_dates = [epoch_to_date(best_x[0])]
t = best_x[0]
for i in range(4):
    t += best_x[i + 1]
    node_dates.append(epoch_to_date(t))

print(f"\nDeparture date    : {node_dates[0]} ")
for i in range(4):
    lname = leg_names[i] if i < len(leg_names) else f"Leg {i}"
    print(f"Arrival at node {i+1} : {node_dates[i+1]}  ({lname.split('→')[-1].strip()})")
    print(f"  └─ ToF           : {tof_to_str(best_x[i+1])}")
sequence = transfer_body_order  # alias for readability below

# Convergence plot
fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(np.arange(number_of_evolutions), np.array(fitness_list).flatten() / 1000)
ax.scatter(np.argmin(fitness_list), np.min(fitness_list) / 1000,
           marker='x', color='r', zorder=10, label='Champion')
ax.set(xlabel='Evolution', ylabel='ΔV [km/s]', title='Best individual over evolutions')
ax.legend(); ax.grid(True); plt.tight_layout(); plt.show()

# Re-evaluate champion trajectory
node_times, leg_fp, node_fp = convert_trajectory_parameters(
    transfer_trajectory_object, pop.champion_x)
transfer_trajectory_object.evaluate(node_times, leg_fp, node_fp)

state_history = transfer_trajectory_object.states_along_trajectory(500)
fly_by_states = np.array([state_history[t] for t in node_times])
state_arr = result2array(state_history)
au = 1.5e11

fig, ax = plt.subplots(figsize=(7, 7))
ax.plot(state_arr[:, 1] / au, state_arr[:, 2] / au, lw=1.2)
colors = ['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple']
for i, name in enumerate(transfer_body_order):
    ax.scatter(fly_by_states[i, 0] / au, fly_by_states[i, 1] / au,
               color=colors[i % len(colors)], label=name, zorder=5, s=60)
ax.scatter([0], [0], color='orange', label='Sun', marker='*', s=150)
ax.set(xlabel='x [AU]', ylabel='y [AU]', aspect='equal')
ax.legend(bbox_to_anchor=(1, 1)); plt.tight_layout(); plt.show()
