# =============================================================
# MGA Trajectory — generated by MGA Trajectory Configurator
# Sequence: Earth → Venus → Earth → Jupiter
# =============================================================
import numpy as np
import matplotlib.pyplot as plt
from typing import List, Tuple
import tudatpy
from tudatpy.trajectory_design import transfer_trajectory
from tudatpy import constants
from tudatpy.dynamics import environment_setup
from tudatpy.util import result2array
from tudatpy.astro.time_representation import DateTime
import pygmo as pg


# -------------------------------------------------------------
# Helper: convert flat parameter list to Tudat format
# -------------------------------------------------------------
def convert_trajectory_parameters(transfer_trajectory_object, trajectory_parameters):
    node_times, leg_free_parameters, node_free_parameters = [], [], []
    departure_time = trajectory_parameters[0]
    times_of_flight_per_leg = trajectory_parameters[1:]
    node_times.append(departure_time)
    accumulated_time = departure_time
    for i in range(transfer_trajectory_object.number_of_nodes - 1):
        accumulated_time += times_of_flight_per_leg[i]
        node_times.append(accumulated_time)
    for i in range(transfer_trajectory_object.number_of_legs):
        leg_free_parameters.append([])
    for i in range(transfer_trajectory_object.number_of_nodes):
        node_free_parameters.append([])
    return node_times, leg_free_parameters, node_free_parameters


# -------------------------------------------------------------
# PyGMO problem class
# -------------------------------------------------------------
class TransferTrajectoryProblem:

    def __init__(self, transfer_trajectory_object,
                 departure_date_lb, departure_date_ub,
                 legs_tof_lb, legs_tof_ub,
                 departure_factor=1.0):
        self.departure_date_lb = departure_date_lb
        self.departure_date_ub = departure_date_ub
        self.legs_tof_lb = legs_tof_lb
        self.legs_tof_ub = legs_tof_ub
        self.departure_factor = departure_factor
        self.transfer_trajectory_function = lambda: transfer_trajectory_object

    def get_bounds(self):
        obj = self.transfer_trajectory_function()
        n = obj.number_of_nodes
        lower_bound = [0.0] * n
        upper_bound = [0.0] * n
        lower_bound[0] = self.departure_date_lb
        upper_bound[0] = self.departure_date_ub
        for i in range(obj.number_of_legs):
            lower_bound[i + 1] = self.legs_tof_lb[i]
            upper_bound[i + 1] = self.legs_tof_ub[i]
        return lower_bound, upper_bound

    def get_number_of_parameters(self):
        return self.transfer_trajectory_function().number_of_nodes

    def fitness(self, trajectory_parameters):
        traj = self.transfer_trajectory_function()
        node_times, leg_fp, node_fp = convert_trajectory_parameters(
            traj, trajectory_parameters)
        try:
            traj.evaluate(node_times, leg_fp, node_fp)
            dv_nodes = traj.delta_v_per_node
            # Departure node weighted by Isp ratio; all other nodes at face value
            weighted_dv = dv_nodes[0] * self.departure_factor + sum(dv_nodes[1:])
        except Exception:
            weighted_dv = 1e10
        return [weighted_dv]


# =============================================================
# Mission configuration
# =============================================================

central_body = "Sun"
transfer_body_order = ["Earth","Venus","Earth","Jupiter"]

# Departure orbit
departure_semi_major_axis = 6650000
departure_eccentricity    = 0

# Arrival orbit
arrival_semi_major_axis = 9861000000
arrival_eccentricity    = 0.94

# Create simplified system of bodies
bodies = environment_setup.create_simplified_system_of_bodies()

# Build leg and node settings
transfer_leg_settings, transfer_node_settings = (
    transfer_trajectory.mga_settings_unpowered_unperturbed_legs(
        transfer_body_order,
        departure_orbit=(departure_semi_major_axis, departure_eccentricity),
        arrival_orbit=(arrival_semi_major_axis, arrival_eccentricity),
    )
)

# Create transfer trajectory object
transfer_trajectory_object = transfer_trajectory.create_transfer_trajectory(
    bodies,
    transfer_leg_settings,
    transfer_node_settings,
    transfer_body_order,
    central_body,
)

# Launch window
departure_date_lb = DateTime(2036, 1, 1).to_epoch()
departure_date_ub = DateTime(2042, 12, 1).to_epoch()

# Time-of-flight bounds [days → seconds]
legs_tof_lb = np.zeros(3)
legs_tof_ub = np.zeros(3)
# Earth → Venus
legs_tof_lb[0] = 20 * constants.JULIAN_DAY
legs_tof_ub[0] = 350 * constants.JULIAN_DAY
# Venus → Earth
legs_tof_lb[1] = 20 * constants.JULIAN_DAY
legs_tof_ub[1] = 1200 * constants.JULIAN_DAY
# Earth → Jupiter
legs_tof_lb[2] = 500 * constants.JULIAN_DAY
legs_tof_ub[2] = 1500 * constants.JULIAN_DAY


# =============================================================
# Optimization setup  (DE — Differential Evolution)
# =============================================================

# Departure engine Isp weighting
# Factor = Isp_cruise / Isp_dep — departure ΔV is scaled by this
# before being summed with all other nodes in the cost function.
ISP_DEP             = 311   # [s]  departure engine
ISP_CRUISE          = 311   # [s]  cruise engine
DEPARTURE_FACTOR    = ISP_CRUISE / ISP_DEP

optimizer = TransferTrajectoryProblem(
    transfer_trajectory_object,
    departure_date_lb, departure_date_ub,
    legs_tof_lb, legs_tof_ub,
    departure_factor=DEPARTURE_FACTOR,
)

prob           = pg.problem(optimizer)
algo           = pg.algorithm(pg.de(gen=10, seed=4444, F=0.5))
population_size = 1000
pop            = pg.population(prob, size=population_size, seed=4444)

# =============================================================
# Run optimization
# =============================================================

number_of_evolutions = 800
individuals_list, fitness_list = [], []

for i in range(number_of_evolutions):
    pop = algo.evolve(pop)
    individuals_list.append(pop.champion_x)
    fitness_list.append(pop.champion_f)

print("Optimization complete")

# =============================================================
# Results
# =============================================================

from datetime import datetime, timedelta

# J2000 epoch: 1 January 2000, 12:00 TT
J2000 = datetime(2000, 1, 1, 12, 0, 0)

def epoch_to_date(epoch_seconds):
    """Convert Tudat epoch (seconds from J2000) to a calendar date string."""
    return (J2000 + timedelta(seconds=epoch_seconds)).strftime("%d %b %Y")

def tof_to_str(tof_seconds):
    """Format a time-of-flight in seconds as 'X days (Y months)'."""
    days = tof_seconds / constants.JULIAN_DAY
    months = days / 30.44
    return f"{days:.1f} days  (~{months:.1f} months)"

best_x = pop.champion_x  # in seconds

# Re-evaluate champion so node/leg delta-V breakdown is available
node_times, leg_fp, node_fp = convert_trajectory_parameters(
    transfer_trajectory_object, best_x)
transfer_trajectory_object.evaluate(node_times, leg_fp, node_fp)

dv_per_node = transfer_trajectory_object.delta_v_per_node  # list, one entry per node

# Node arrival dates
node_dates = [epoch_to_date(best_x[0])]
t = best_x[0]
for i in range(3):
    t += best_x[i + 1]
    node_dates.append(epoch_to_date(t))

print("\n--- Champion ---")
print(f"Total ΔV : {pop.champion_f[0]:.2f} m/s  ({pop.champion_f[0]/1000:.3f} km/s)")
print(f"\n{'Node':<6} {'Body':<10} {'Date':<14} {'ΔV [m/s]':>10}  Time of flight")
print("-" * 60)
print(f"{'0':<6} {transfer_body_order[0]:<10} {node_dates[0]:<14} {dv_per_node[0]:>10.2f}  (departure)")
for i in range(3):
    body = transfer_body_order[i + 1]
    tof_str = tof_to_str(best_x[i + 1])
    print(f"{i+1:<6} {body:<10} {node_dates[i+1]:<14} {dv_per_node[i+1]:>10.2f}  after {tof_str}")

# Convergence plot
fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(np.arange(number_of_evolutions), np.array(fitness_list).flatten() / 1000)
ax.scatter(np.argmin(fitness_list), np.min(fitness_list) / 1000,
           marker='x', color='r', zorder=10, label='Champion')
ax.set(xlabel='Evolution', ylabel='ΔV [km/s]', title='Best individual over evolutions')
ax.legend(); ax.grid(True); plt.tight_layout(); plt.show()

state_history = transfer_trajectory_object.states_along_trajectory(500)
fly_by_states = np.array([state_history[t] for t in node_times])
state_arr = result2array(state_history)
au = 1.5e11

fig, ax = plt.subplots(figsize=(7, 7))
ax.plot(state_arr[:, 1] / au, state_arr[:, 2] / au, lw=1.2)
colors = ['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple']
for i, name in enumerate(transfer_body_order):
    ax.scatter(fly_by_states[i, 0] / au, fly_by_states[i, 1] / au,
               color=colors[i % len(colors)], label=name, zorder=5, s=60)
ax.scatter([0], [0], color='orange', label='Sun', marker='*', s=150)
ax.set(xlabel='x [AU]', ylabel='y [AU]', aspect='equal')
ax.legend(bbox_to_anchor=(1, 1)); plt.tight_layout(); plt.show()


# =============================================================
# Monthly launch-window sweep
# =============================================================
import pandas as pd

def sweep_monthly_launches(
    transfer_trajectory_object,
    legs_tof_lb,
    legs_tof_ub,
    sweep_start=datetime(2036, 1, 1),
    sweep_end=datetime(2042, 12, 1),
    window_half_days=15,
):
    """
    Run a full DE optimisation for every calendar month in the sweep window.
    For each month the departure window is:
        [1st-of-month  −  window_half_days,  1st-of-month  +  window_half_days]

    Returns
    -------
    pd.DataFrame
        launch_date      – best departure date found (datetime)
        delta_v_ms       – total ΔV of champion [m/s]
        total_tof_days   – sum of all leg ToFs [days]
    """
    JULIAN_DAY_S = constants.JULIAN_DAY

    # Build list of 1st-of-month dates between sweep_start and sweep_end
    candidate_dates = []
    cur = sweep_start.replace(day=1)
    while cur <= sweep_end:
        candidate_dates.append(cur)
        cur = (cur.replace(day=28) + timedelta(days=4)).replace(day=1)  # safe +1 month

    records = []
    n = len(candidate_dates)

    for idx, date in enumerate(candidate_dates):
        mid_epoch = (date - J2000).total_seconds()
        dep_lb    = mid_epoch - window_half_days * JULIAN_DAY_S
        dep_ub    = mid_epoch + window_half_days * JULIAN_DAY_S

        opt_sweep = TransferTrajectoryProblem(
            transfer_trajectory_object,
            dep_lb, dep_ub,
            legs_tof_lb, legs_tof_ub,
            departure_factor=DEPARTURE_FACTOR,
        )
        prob_s = pg.problem(opt_sweep)
        algo_s = pg.algorithm(pg.de(gen=10, seed=4444, F=0.5))
        pop_s  = pg.population(prob_s, size=200, seed=4444)

        for _ in range(800):
            pop_s = algo_s.evolve(pop_s)

        best_x_s      = pop_s.champion_x
        dv_s          = pop_s.champion_f[0]
        dep_date      = J2000 + timedelta(seconds=float(best_x_s[0]))
        total_tof     = float(np.sum(best_x_s[1:])) / JULIAN_DAY_S

        print(f"[{idx+1:>3}/{n}]  {date.strftime('%b %Y')}  →  "
              f"departure {dep_date.strftime('%d %b %Y')}  |  "
              f"ΔV {dv_s/1000:6.2f} km/s  |  ToF {total_tof:.0f} days")

        # Re-evaluate champion to extract per-node ΔVs
        node_times_s, leg_fp_s, node_fp_s = convert_trajectory_parameters(
            transfer_trajectory_object, best_x_s)
        transfer_trajectory_object.evaluate(node_times_s, leg_fp_s, node_fp_s)
        dv_nodes_s = transfer_trajectory_object.delta_v_per_node

        record = {
            "launch_date"    : dep_date,
            "delta_v_ms"     : dv_s,
            "total_tof_days" : total_tof,
        }
        for ni, dv_n in enumerate(dv_nodes_s):
            record[f"dv_node_{ni}_{transfer_body_order[ni]}_ms"] = round(dv_n, 2)
        records.append(record)

    return pd.DataFrame(records)


def plot_sweep(df: pd.DataFrame) -> None:
    """Plot ΔV and total ToF versus launch date on a dual-axis chart."""
    fig, ax1 = plt.subplots(figsize=(12, 5))

    c_dv  = "#2563eb"   # blue  – ΔV
    c_tof = "#ea580c"   # orange – ToF

    ax1.plot(df["launch_date"], df["delta_v_ms"] / 1000,
             color=c_dv, marker="o", ms=4, lw=1.5, label="ΔV [km/s]")
    ax1.set_xlabel("Launch date")
    ax1.set_ylabel("Total ΔV  [km/s]", color=c_dv)
    ax1.tick_params(axis="y", labelcolor=c_dv)
    ax1.yaxis.label.set_color(c_dv)

    ax2 = ax1.twinx()
    ax2.plot(df["launch_date"], df["total_tof_days"],
             color=c_tof, marker="s", ms=4, lw=1.5, linestyle="--", label="ToF [days]")
    ax2.set_ylabel("Total transfer time  [days]", color=c_tof)
    ax2.tick_params(axis="y", labelcolor=c_tof)

    # Mark best ΔV launch
    best_row = df.loc[df["delta_v_ms"].idxmin()]
    ax1.scatter([best_row["launch_date"]], [best_row["delta_v_ms"] / 1000],
                color="red", zorder=5, s=80, label=f"Best  {best_row['delta_v_ms']/1000:.2f} km/s")

    lines  = ax1.get_lines() + ax2.get_lines() + ax1.collections[:1]
    labels = [l.get_label() for l in lines]
    ax1.legend(lines, labels, loc="upper right")

    transfer_name = ""
    for i in transfer_body_order[1:-1]:
        transfer_name += i[0]
    ax1.set_title(f"Monthly launch opportunities  " + transfer_name)
    ax1.grid(True, alpha=0.3)
    fig.autofmt_xdate(rotation=30)
    plt.tight_layout()
    plt.show()


# --- Run the sweep ---
df_sweep = sweep_monthly_launches(
    transfer_trajectory_object,
    legs_tof_lb,
    legs_tof_ub,
)

print("\n", df_sweep.to_string(index=False))
plot_sweep(df_sweep)

# Save to CSV — results/ folder next to this script
import os as _os
transfer_name = ""
for i in transfer_body_order[1:-1]:
    transfer_name += i[0]
transfer_name += ".csv"
results_dir = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "results")
_os.makedirs(results_dir, exist_ok=True)
csv_path = _os.path.join(results_dir, transfer_name)
df_sweep.to_csv(csv_path, index=False)
print(f"Saved: {csv_path}")
