



# =============================================================
# MGA Trajectory — generated by MGA Trajectory Configurator
# Sequence: Earth → Venus → Earth → Earth → Jupiter
# =============================================================
import numpy as np
import matplotlib.pyplot as plt
from typing import List, Tuple
import tudatpy
from tudatpy.trajectory_design import transfer_trajectory
from tudatpy import constants
from tudatpy.dynamics import environment_setup
from tudatpy.util import result2array
from tudatpy.astro.time_representation import DateTime
import pygmo as pg



# -------------------------------------------------------------
# Helper: convert flat parameter list to Tudat format
# -------------------------------------------------------------
def convert_trajectory_parameters(transfer_trajectory_object, trajectory_parameters):
    node_times, leg_free_parameters, node_free_parameters = [], [], []
    departure_time = trajectory_parameters[0]
    times_of_flight_per_leg = trajectory_parameters[1:]
    node_times.append(departure_time)
    accumulated_time = departure_time
    for i in range(transfer_trajectory_object.number_of_nodes - 1):
        accumulated_time += times_of_flight_per_leg[i]
        node_times.append(accumulated_time)
    for i in range(transfer_trajectory_object.number_of_legs):
        leg_free_parameters.append([])
    for i in range(transfer_trajectory_object.number_of_nodes):
        node_free_parameters.append([])
    return node_times, leg_free_parameters, node_free_parameters


# -------------------------------------------------------------
# PyGMO problem class
# -------------------------------------------------------------
class TransferTrajectoryProblem:

    def __init__(self, transfer_trajectory_object,
                 departure_date_lb, departure_date_ub,
                 legs_tof_lb, legs_tof_ub,
                 departure_factor=1.0):
        self.departure_date_lb = departure_date_lb
        self.departure_date_ub = departure_date_ub
        self.legs_tof_lb = legs_tof_lb
        self.legs_tof_ub = legs_tof_ub
        self.departure_factor = departure_factor
        self.transfer_trajectory_function = lambda: transfer_trajectory_object

    def get_bounds(self):
        obj = self.transfer_trajectory_function()
        n = obj.number_of_nodes
        lower_bound = [0.0] * n
        upper_bound = [0.0] * n
        lower_bound[0] = self.departure_date_lb
        upper_bound[0] = self.departure_date_ub
        for i in range(obj.number_of_legs):
            lower_bound[i + 1] = self.legs_tof_lb[i]
            upper_bound[i + 1] = self.legs_tof_ub[i]
        return lower_bound, upper_bound

    def get_number_of_parameters(self):
        return self.transfer_trajectory_function().number_of_nodes

    def fitness(self, trajectory_parameters):
        traj = self.transfer_trajectory_function()
        node_times, leg_fp, node_fp = convert_trajectory_parameters(
            traj, trajectory_parameters)
        try:
            traj.evaluate(node_times, leg_fp, node_fp)
            dv_nodes = traj.delta_v_per_node
            # Departure node weighted by Isp ratio; all other nodes at face value
            weighted_dv = dv_nodes[0] * self.departure_factor + sum(dv_nodes[1:])
        except Exception:
            weighted_dv = 1e10
        return [weighted_dv]


# =============================================================
# Mission configuration
# =============================================================

central_body = "Sun"
transfer_body_order = ["Earth","Venus","Earth","Earth","Jupiter"]

# Departure orbit
departure_semi_major_axis = 6650000
departure_eccentricity    = 0

# Arrival orbit
arrival_semi_major_axis = 9861000000
arrival_eccentricity    = 0.94

# Create simplified system of bodies
bodies = environment_setup.create_simplified_system_of_bodies()

# Build leg and node settings
transfer_leg_settings, transfer_node_settings = (
    transfer_trajectory.mga_settings_unpowered_unperturbed_legs(
        transfer_body_order,
        departure_orbit=(departure_semi_major_axis, departure_eccentricity),
        arrival_orbit=(arrival_semi_major_axis, arrival_eccentricity),
    )
)

# Create transfer trajectory object
transfer_trajectory_object = transfer_trajectory.create_transfer_trajectory(
    bodies,
    transfer_leg_settings,
    transfer_node_settings,
    transfer_body_order,
    central_body,
)

# Launch window
departure_date_lb = DateTime(1989, 10, 15).to_epoch()
departure_date_ub = DateTime(1989, 11, 15).to_epoch()

# Time-of-flight bounds [days → seconds]
legs_tof_lb = np.zeros(4)
legs_tof_ub = np.zeros(4)
# Earth → Venus
legs_tof_lb[0] = 20 * constants.JULIAN_DAY
legs_tof_ub[0] = 350 * constants.JULIAN_DAY
# Venus → Earth
legs_tof_lb[1] = 20 * constants.JULIAN_DAY
legs_tof_ub[1] = 600 * constants.JULIAN_DAY
# Earth → Earth
legs_tof_lb[2] = 300 * constants.JULIAN_DAY
legs_tof_ub[2] = 1000 * constants.JULIAN_DAY
# Earth → Jupiter
legs_tof_lb[3] = 500 * constants.JULIAN_DAY
legs_tof_ub[3] = 1500 * constants.JULIAN_DAY


# =============================================================
# Optimization setup  (DE — Differential Evolution)
# =============================================================

# Departure engine Isp weighting
# Factor = Isp_cruise / Isp_dep — departure ΔV is scaled by this
# before being summed with all other nodes in the cost function.
ISP_DEP             = 311   # [s]  departure engine
ISP_CRUISE          = 311   # [s]  cruise engine
DEPARTURE_FACTOR    = ISP_CRUISE / ISP_DEP

optimizer = TransferTrajectoryProblem(
    transfer_trajectory_object,
    departure_date_lb, departure_date_ub,
    legs_tof_lb, legs_tof_ub,
    departure_factor=DEPARTURE_FACTOR,
)

prob           = pg.problem(optimizer)
algo           = pg.algorithm(pg.de(gen=10, seed=4444, F=0.5))
population_size = 100
pop            = pg.population(prob, size=population_size, seed=4444)

# =============================================================
# Run optimization
# =============================================================

number_of_evolutions = 800
individuals_list, fitness_list = [], []

for i in range(number_of_evolutions):
    pop = algo.evolve(pop)
    individuals_list.append(pop.champion_x)
    fitness_list.append(pop.champion_f)

print("Optimization complete")

# =============================================================
# Results
# =============================================================

from datetime import datetime, timedelta

# J2000 epoch: 1 January 2000, 12:00 TT
J2000 = datetime(2000, 1, 1, 12, 0, 0)

def epoch_to_date(epoch_seconds):
    """Convert Tudat epoch (seconds from J2000) to a calendar date string."""
    return (J2000 + timedelta(seconds=epoch_seconds)).strftime("%d %b %Y")

def tof_to_str(tof_seconds):
    """Format a time-of-flight in seconds as 'X days (Y months)'."""
    days = tof_seconds / constants.JULIAN_DAY
    months = days / 30.44
    return f"{days:.1f} days  (~{months:.1f} months)"

best_x = pop.champion_x  # in seconds

# Re-evaluate champion so node/leg delta-V breakdown is available
node_times, leg_fp, node_fp = convert_trajectory_parameters(
    transfer_trajectory_object, best_x)
transfer_trajectory_object.evaluate(node_times, leg_fp, node_fp)

dv_per_node = transfer_trajectory_object.delta_v_per_node  # list, one entry per node

# Node arrival dates
node_dates = [epoch_to_date(best_x[0])]
t = best_x[0]
for i in range(4):
    t += best_x[i + 1]
    node_dates.append(epoch_to_date(t))

print("\n--- Champion ---")
print(f"Total ΔV : {pop.champion_f[0]:.2f} m/s  ({pop.champion_f[0]/1000:.3f} km/s)")
print(f"\n{'Node':<6} {'Body':<10} {'Date':<14} {'ΔV [m/s]':>10}  Time of flight")
print("-" * 60)
print(f"{'0':<6} {transfer_body_order[0]:<10} {node_dates[0]:<14} {dv_per_node[0]:>10.2f}  (departure)")
for i in range(4):
    body = transfer_body_order[i + 1]
    tof_str = tof_to_str(best_x[i + 1])
    print(f"{i+1:<6} {body:<10} {node_dates[i+1]:<14} {dv_per_node[i+1]:>10.2f}  after {tof_str}")

# Convergence plot
fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(np.arange(number_of_evolutions), np.array(fitness_list).flatten() / 1000)
ax.scatter(np.argmin(fitness_list), np.min(fitness_list) / 1000,
           marker='x', color='r', zorder=10, label='Champion')
ax.set(xlabel='Evolution', ylabel='ΔV [km/s]', title='Best individual over evolutions')
ax.legend(); ax.grid(True); plt.tight_layout(); plt.show()

state_history = transfer_trajectory_object.states_along_trajectory(500)
fly_by_states = np.array([state_history[t] for t in node_times])
state_arr = result2array(state_history)
au = 1.5e11

fig, ax = plt.subplots(figsize=(9, 9))

# ── Planetary orbit reference circles ────────────────────────────────────────
PLANET_ORBITS = {'Venus': 0.723, 'Earth': 1.000, 'Mars': 1.524, 'Jupiter': 5.203}
_theta = np.linspace(0, 2 * np.pi, 360)
for _pname, _r in PLANET_ORBITS.items():
    ax.plot(_r * np.cos(_theta), _r * np.sin(_theta),
            color='gray', lw=0.6, ls=':', alpha=0.55, zorder=1)
    ax.text(_r * np.cos(np.radians(262)), _r * np.sin(np.radians(262)),
            _pname, fontsize=6.5, color='gray', alpha=0.75,
            ha='left', va='bottom', zorder=2)

# ── Transfer arc ─────────────────────────────────────────────────────────────
ax.plot(state_arr[:, 1] / au, state_arr[:, 2] / au,
        lw=1, color='steelblue', zorder=3, label='Trajectory')

# ── Maneuver nodes with date labels ──────────────────────────────────────────
_node_colors = ['tab:blue','tab:orange','tab:green','tab:red',
                'tab:purple','tab:brown','tab:pink','tab:cyan']
offset_planet = 15
counter1 = 0

for i, (_bname, _t) in enumerate(zip(transfer_body_order, node_times)):
    _xn = fly_by_states[i, 0] / au
    _yn = fly_by_states[i, 1] / au
    _col = _node_colors[i % len(_node_colors)]
    _date_str = (J2000 + timedelta(seconds=float(_t))).strftime('%d %b %Y')
    ax.scatter(_xn, _yn, color=_col, s=65, zorder=6, label=_bname)
    if _bname == 'Earth':
        if counter1 == 2:
            offset_planet = -75
        counter1 += 1
    ax.annotate(f'{_bname}\n{_date_str}',
                xy=(_xn, _yn), xytext=(offset_planet, 15), textcoords='offset points',
                fontsize=10, color=_col, zorder=7,
                arrowprops=dict(arrowstyle='-', color=_col, lw=0.5))

# ── Sun ──────────────────────────────────────────────────────────────────────
ax.scatter([0], [0], color='orange', marker='*', s=220, zorder=6, label='Sun')

# ── Closest approach to the Sun (perihelion of the transfer arc) ─────────────
_r_traj  = np.sqrt(state_arr[:, 1]**2 + state_arr[:, 2]**2)
_idx_min = np.argmin(_r_traj)
_r_min   = _r_traj[_idx_min] / au
_xp = state_arr[_idx_min, 1] / au
_yp = state_arr[_idx_min, 2] / au
ax.scatter(_xp, _yp, color='crimson', marker='v', s=80, zorder=7,
           label=f'Perihelion  {_r_min:.3f} AU')
ax.annotate(f'Perihelion\n{_r_min:.3f} AU',
            xy=(_xp, _yp), xytext=(10, -16), textcoords='offset points',
            fontsize=7.5, color='crimson', zorder=8,
            arrowprops=dict(arrowstyle='->', color='crimson', lw=0.8))

ax.set(xlabel='x  [AU]', ylabel='y  [AU]', aspect='equal',
        #title=f"Transfer trajectory  ·  {' → '.join(transfer_body_order)}"
       )
ax.legend(loc='lower left', fontsize=8)
ax.grid(True, alpha=0.15)
ax.set_xlim(-2.5,2.1)
ax.set_ylim(-6,2)
plt.axis("off")
plt.tight_layout()
plt.show()

